--- #YAML:1.0
name:                FabForce-DBDesigner4
version:             0.11
abstract:            Parse/Analyse XML-Files created by DBDesigner 4 (FabForce)
license:             perl
author:              
    - Renee Baecker <module@renee-baecker.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          1.04
    Exporter:                      5.58
    IO::File:                      1.1
    XML::Twig:                     3.17
    XML::Writer:                   0.6
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
